server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library-app
    username: demo_user
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      format-sql: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

library:
  app:
    jwtSecret: javanarlarLibrary@8
    jwtExpirationMs: 86400000

info:
  application:
    name: 'Book Loan Center Application'
    description: 'This is Book Loan Center Backend App dev by javafadu'
    version: '@project.version@'
